In [19]:
import pandas as pd
import numpy as np
import random
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [20]:
churn_2_classes = pd.read_csv('./data/churn_2_classes.csv', index_col=0)
churn_3_classes = pd.read_csv('./data/churn_3_classes.csv', index_col=0)

In [21]:
churn_2_classes

days_since_last_order median_order_type  days_since_last_contact  \
2288                      1   raw_ingredients                       12   
869                       4    finished_goods                        6   
4619                      4   raw_ingredients                        1   
5651                     12   raw_ingredients                        9   
6237                     11   raw_ingredients                        4   
...                     ...               ...                      ...   
3841                      7   raw_ingredients                        2   
4279                      5   raw_ingredients                        7   
8813                      7    finished_goods                       12   
8294                      5   raw_ingredients                        2   
7855                      8    finished_goods                        6   

      monthly_mean_order_vol  yearly_mean_cust_rev  status  
2288                    1483                  1466  active  
869                     1400                  1279  active  
4619                    1419                  1218  active  
5651                    1184                  1443  active  
6237                     614                   914  active  
...                      ...                   ...     ...  
3841                    1362                  1277  active  
4279                     637                   635  active  
8813                     641                   777  active  
8294                     519                  1290  active  
7855                     522                   947  active  

[11000 rows x 6 columns]

In [22]:
churn_3_classes

days_since_last_order median_order_type  days_since_last_contact  \
9728                      2   raw_ingredients                       10   
3374                     10   raw_ingredients                        4   
884                      11    finished_goods                        7   
8910                     12   raw_ingredients                       14   
9075                     10   raw_ingredients                        6   
...                     ...               ...                      ...   
8113                     12   raw_ingredients                       12   
9809                      6   raw_ingredients                        5   
7739                      9   raw_ingredients                        4   
256                       9    finished_goods                       11   
2355                      7   raw_ingredients                        4   

      monthly_mean_order_vol  yearly_mean_cust_rev  status  
9728                     813                  1206  active  
3374                    1402                  1246  active  
884                      635                  1479  active  
8910                     771                   809  active  
9075                    1362                  1185  active  
...                      ...                   ...     ...  
8113                    1127                   560  active  
9809                    1280                   897  active  
7739                    1147                   549  active  
256                     1100                  1322  active  
2355                    1497                  1018  active  

[12000 rows x 6 columns]

In [23]:
X = churn_2_classes[['days_since_last_order', 'days_since_last_contact', 'monthly_mean_order_vol', 'yearly_mean_cust_rev']]
y = churn_2_classes[['status']]
le = preprocessing.LabelEncoder()
le.fit(y)
y.loc[:,'status'] = le.transform(churn_2_classes['status'])
y = y['status']

/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/benjamin/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1843: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [24]:
X

days_since_last_order  days_since_last_contact  monthly_mean_order_vol  \
2288                      1                       12                    1483   
869                       4                        6                    1400   
4619                      4                        1                    1419   
5651                     12                        9                    1184   
6237                     11                        4                     614   
...                     ...                      ...                     ...   
3841                      7                        2                    1362   
4279                      5                        7                     637   
8813                      7                       12                     641   
8294                      5                        2                     519   
7855                      8                        6                     522   

      yearly_mean_cust_rev  
2288                  1466  
869                   1279  
4619                  1218  
5651                  1443  
6237                   914  
...                    ...  
3841                  1277  
4279                   635  
8813                   777  
8294                  1290  
7855                   947  

[11000 rows x 4 columns]

In [25]:
y

2288    0
869     0
4619    0
5651    0
6237    0
       ..
3841    0
4279    0
8813    0
8294    0
7855    0
Name: status, Length: 11000, dtype: int64

In [26]:
ss = ShuffleSplit(n_splits=3, test_size=0.25, random_state=0)
gbc = GradientBoostingClassifier(n_estimators=100, max_depth=20)
svc = LinearSVC(max_iter=10000)

gbc_scores = []
svc_scores = []

In [27]:
for train_index, test_index in ss.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    gbc.fit(X_train, y_train)
    svc.fit(X_train, y_train)
    
    gbc_y_pred = gbc.predict( X_test )
    svc_y_pred = svc.predict( X_test )

    gbc_scores.append(accuracy_score(gbc_y_pred, y_test))
    svc_scores.append(accuracy_score(svc_y_pred, y_test))

/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [28]:
gbc_scores

[0.9665454545454546, 0.9672727272727273, 0.972]

In [29]:
svc_scores

[0.5218181818181818, 0.9101818181818182, 0.7916363636363636]

In [30]:
confusion_matrix(gbc_y_pred, y_test)

array([[2485,   66],
       [  11,  188]])

In [31]:
confusion_matrix(svc_y_pred, y_test)

array([[1954,   31],
       [ 542,  223]])

In [32]:
X = churn_3_classes[['days_since_last_order', 'days_since_last_contact', 'monthly_mean_order_vol', 'yearly_mean_cust_rev']]
y = churn_3_classes[['status']]
le = preprocessing.LabelEncoder()
le.fit(y)
y.loc[:,'status'] = le.transform(churn_3_classes['status'])
y = y['status']

/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/benjamin/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1843: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [33]:
ss = ShuffleSplit(n_splits=3, test_size=0.25, random_state=0)
gbc = GradientBoostingClassifier(n_estimators=100, max_depth=20)
svc = LinearSVC(max_iter=10000)

gbc_scores = []
svc_scores = []

In [34]:
for train_index, test_index in ss.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    gbc.fit(X_train, y_train)
    svc.fit(X_train, y_train)
    
    gbc_y_pred = gbc.predict( X_test )
    svc_y_pred = svc.predict( X_test )

    gbc_scores.append(accuracy_score(gbc_y_pred, y_test))
    svc_scores.append(accuracy_score(svc_y_pred, y_test))

/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [35]:
gbc_scores

[0.96, 0.9583333333333334, 0.9563333333333334]

In [36]:
svc_scores

[0.898, 0.8956666666666667, 0.8993333333333333]

In [37]:
confusion_matrix(gbc_y_pred, y_test)

array([[2498,   90,    4],
       [   8,  161,   16],
       [   0,   13,  210]])

In [38]:
confusion_matrix(svc_y_pred, y_test)

array([[2506,  243,   38],
       [   0,    0,    0],
       [   0,   21,  192]])

In [39]:
ss = ShuffleSplit(n_splits=3, test_size=0.25, random_state=0)
gbc = GradientBoostingClassifier(n_estimators=100, max_depth=20)
svc = LinearSVC(max_iter=10000, class_weight='balanced')

gbc_scores = []
svc_scores = []

In [40]:
for train_index, test_index in ss.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    gbc.fit(X_train, y_train)
    svc.fit(X_train, y_train)
    
    gbc_y_pred = gbc.predict( X_test )
    svc_y_pred = svc.predict( X_test )

    gbc_scores.append(accuracy_score(gbc_y_pred, y_test))
    svc_scores.append(accuracy_score(svc_y_pred, y_test))

/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/benjamin/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [41]:
gbc_scores

[0.958, 0.9576666666666667, 0.9556666666666667]

In [42]:
svc_scores

[0.8963333333333333, 0.8846666666666667, 0.8916666666666667]

In [43]:
confusion_matrix(svc_y_pred, y_test)

array([[2506,  260,   61],
       [   0,    0,    0],
       [   0,    4,  169]])

In [44]:
#complete a model selection for this gbc vs linearsvc...

In [ ]:
#plot decision boundary using example here
https://scikit-learn.org/stable/auto_examples/tree/plot_iris_dtc.html